[app]
PRJ_TITLE = Free CMS
LANGUAGES = de.en
GEN_LANG = en
STD_LANG = de

[design]
LAYOUT = default
COLORS = default
EDITOR = default

[security]
TIMEOUT = 15
SECRET = anyString

[environment]
TIMEZONE = Europe/Vienna
WWW_USER = www-data
CSS_URL = x.css.php
CMS_URL = https://cms.glaubeistmehr.at
X_TOOLS = /xtools

[debugging]
ERR_SHOW = 0
